# agent.py (SAFE MODE)

from scraper import duckduckgo_search, fetch_page_text
from summarizer import summarize

import time
import textwrap
from fpdf import FPDF
import os
import re

# ---- RAG MEMORY IMPORTS ----
from rag_memory import init_and_connect, upsert_summary
import os


# ============================================================
# FLAGS: Detect whether APIs are enabled
# ============================================================
OPENAI_ENABLED = bool(os.environ.get("OPENAI_API_KEY"))
PINECONE_ENABLED = bool(os.environ.get("PINECONE_API_KEY"))


# ============================================================
# CLEAN TEXT FOR PDF
# ============================================================
def clean_for_pdf(text):
    text = re.sub(r'[\U00010000-\U0010ffff]', '', text)
    replacements = {
        "—": "-", "–": "-", "…": "...",
        "‘": "'", "’": "'", "“": '"', "”": '"'
    }
    for bad, good in replacements.items():
        text = text.replace(bad, good)

    text = text.encode("latin-1", "ignore").decode("latin-1")
    return text


# ============================================================
# SAVE REPORT
# ============================================================
def save_txt_md_pdf(report_text: str, out_base: str = "research_report"):

    os.makedirs("reports", exist_ok=True)
    txt_path = os.path.join("reports", out_base + ".txt")
    md_path = os.path.join("reports", out_base + ".md")
    pdf_path = os.path.join("reports", out_base + ".pdf")

    with open(txt_path, "w", encoding="utf-8") as f:
        f.write(report_text)

    with open(md_path, "w", encoding="utf-8") as f:
        f.write(report_text)

    pdf_text = clean_for_pdf(report_text)

    pdf = FPDF(unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_font("Arial", size=11)

    wrapper = textwrap.TextWrapper(width=110)

    for paragraph in pdf_text.splitlines():
        if paragraph.strip() == "":
            pdf.ln(5)
        else:
            for line in wrapper.wrap(paragraph):
                pdf.multi_cell(0, 5, line)

    pdf.output(pdf_path)

    return {"txt": txt_path, "md": md_path, "pdf": pdf_path}


# ============================================================
# AUTONOMOUS RESEARCH AGENT
# ============================================================
class ResearchAgent:

    def __init__(self, query, max_articles=3):
        self.query = query
        self.max_articles = max_articles
        self.collected_summaries = []
        self.visited_urls = []

    # ---------------------------------------------
    # Search Web
    # ---------------------------------------------
    def search_web(self):
        print("\n Searching web for:", self.query)
        results = duckduckgo_search(self.query)
        print(f" Found {len(results)} results")
        return results

    # ---------------------------------------------
    # Extract + Summarize + Store in Memory
    # ---------------------------------------------
    def extract_and_summarize(self, url, title):
        print(f"\n Fetching: {title}")
        print(f" URL: {url}")

        text = fetch_page_text(url)

        if len(text.strip()) < 50:
            print(" Skipping: Not enough text")
            return None

        print("\n Summarizing page...")
        summary = summarize(text)

        # ---- Store summary in Pinecone (if enabled) ----
        if PINECONE_ENABLED:
            try:
                upsert_summary(title=title, url=url, summary=summary, source="web")
            except Exception as e:
                print("❌ Pinecone upsert failed:", e)
        else:
            print("⚠️ Memory disabled by admin (Sudheer). Not storing in Pinecone.")

        self.collected_summaries.append({
            "title": title,
            "url": url,
            "summary": summary
        })

        return summary

    # ---------------------------------------------
    # Build Final Report
    # ---------------------------------------------
    def create_final_report(self):
        print("\n Creating FINAL RESEARCH REPORT...")

        report = f" Research Topic: {self.query}\n\n"

        for item in self.collected_summaries:
            report += f" {item['title']}\n"
            report += f"URL: {item['url']}\n\n"
            report += str(item['summary']) + "\n\n"

        report += "---\nGenerated by Autonomous Research Assistant\n"
        report += f"Number of sources: {len(self.collected_summaries)}\n"

        return report

    # ---------------------------------------------
    # If only 1 article found → expand search
    # ---------------------------------------------
    def needs_more_research(self):
        return len(self.collected_summaries) < 2

    # ---------------------------------------------
    # RUN AGENT
    # ---------------------------------------------
    def run(self):
        results = self.search_web()
        count = 0

        for item in results:
            if count >= self.max_articles:
                break

            url = item["url"].lower()
            title = item["title"]

            if url in self.visited_urls:
                continue
            if "duckduckgo-help-pages" in url:
                continue
            if "ads-by-microsoft" in url:
                continue
            if title.lower() == "more info":
                continue

            summary = self.extract_and_summarize(url, title)
            self.visited_urls.append(url)

            if summary:
                count += 1

            time.sleep(1)

        if self.needs_more_research():
            print("\n Agent: Not enough data → Expanding search...")
            self.max_articles += 2
            return self.run()

        return self.create_final_report()


# ============================================================
# MAIN (for direct CLI test)
# ============================================================
if __name__ == "__main__":
    query = "AI careers 2025"

    if PINECONE_ENABLED:
        print("🔧 Initializing Pinecone memory...")
        try:
            init_and_connect("research-memory")
        except Exception as e:
            print("❌ Pinecone initialization failed:", e)
    else:
        print("⚠️ Pinecone disabled by admin (Sudheer).")

    agent = ResearchAgent(query=query, max_articles=2)
    final_report = agent.run()

    print("\n============================")
    print(" FINAL RESEARCH REPORT")
    print("============================\n")
    print(final_report)

    saved = save_txt_md_pdf(final_report, out_base="research_report")
    print("\nSaved files:")
    for k, v in saved.items():
        print(f" - {k}: {v}")
